name: Deploy website
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache the dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependency-caching-${{  hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.anyidname.outputs.anyname }}
      simple-output: ${{ steps.simpleoutput.outputs.mykey }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache the dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependency-caching-${{  hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: publish js file name
        id: anyidname
        run: find dist/assets/*.js -type f -execdir echo 'anyname={}' >> $GITHUB_OUTPUT ';'
      - name: setting simple output
        id: simpleoutput
        run: echo 'mykey=myvalue' >> $GITHUB_OUTPUT
      - name: Output contents
        run: |
            echo "running ls"
            ls
            echo "running pwd"
            pwd
            echo "running ls dist"
            ls dist
            echo "running ls dist/assets/"
            ls dist/assets/
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: outputs
        run: |
          echo "${{ needs.build.outputs.script-file }}"
          echo "${{ needs.build.outputs.simple-output }}"
      # - name: Output contents
      #   run: |
      #       echo "running ls"
      #       ls
      #       echo "running pwd"
      #       pwd
      #       echo "running ls dist"
      #       ls dist
      #       echo "running ls dist/"
      #       ls dist/
      - name: Deploy
        run: echo "Deploying..."
